"""
Export Service
Handles code export as ZIP and pitch materials export.
"""

import os
import zipfile
from io import BytesIO
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime


class ExportService:
    """
    Generates export packages for the hackathon project.
    Creates ZIP files with generated code and pitch materials.
    """

    def __init__(self, export_dir: str = "data/exports"):
        self.export_dir = Path(export_dir)
        self.export_dir.mkdir(parents=True, exist_ok=True)

    def export_code_zip(
        self,
        session_id: str,
        code_artifacts: Dict[str, dict],
        title: str = "project",
    ) -> str:
        """
        Create ZIP file with all generated code.

        Args:
            session_id: Session identifier
            code_artifacts: Dictionary of filepath -> content
            title: Project title (used in filename)

        Returns:
            Path to the created ZIP file
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{title.replace(' ', '_')}_{session_id}_{timestamp}.zip"
        filepath = self.export_dir / filename

        with zipfile.ZipFile(filepath, "w", zipfile.ZIP_DEFLATED) as zf:
            # Add README
            readme_content = f"""# {title}
Generated by Hackathon Copilot
Session: {session_id}
Date: {datetime.now().isoformat()}

## Files
"""
            for file_path in code_artifacts.keys():
                readme_content += f"- {file_path}\n"

            zf.writestr("README.md", readme_content)

            # Add code files
            for file_path, file_data in code_artifacts.items():
                content = file_data.get("content", "") if isinstance(file_data, dict) else str(file_data)
                zf.writestr(file_path, content)

        return str(filepath)

    def export_pitch_materials(
        self,
        session_id: str,
        narrative: dict,
        slides: list,
        script: list,
        title: str = "project",
    ) -> str:
        """
        Create text files with pitch materials.

        Returns:
            Path to the created ZIP file
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"pitch_{title.replace(' ', '_')}_{session_id}_{timestamp}.zip"
        filepath = self.export_dir / filename

        with zipfile.ZipFile(filepath, "w", zipfile.ZIP_DEFLATED) as zf:
            # Narrative
            if narrative:
                narrative_text = self._format_narrative(narrative)
                zf.writestr("01_narrative.txt", narrative_text)

            # Slides
            if slides:
                slides_text = self._format_slides(slides)
                zf.writestr("02_slides_outline.txt", slides_text)

            # Script
            if script:
                script_text = self._format_script(script)
                zf.writestr("03_speaker_script.txt", script_text)

        return str(filepath)

    def _format_narrative(self, narrative: dict) -> str:
        """Format narrative as text."""
        lines = ["NARRATIVE ARC", "=" * 50, ""]
        if isinstance(narrative, dict):
            for key, value in narrative.items():
                lines.append(f"{key.upper()}:")
                lines.append(f"{value}")
                lines.append("")
        else:
            lines.append(str(narrative))
        return "\n".join(lines)

    def _format_slides(self, slides: list) -> str:
        """Format slides as text."""
        lines = ["SLIDE DECK OUTLINE", "=" * 50, ""]
        for slide in slides:
            if isinstance(slide, dict):
                lines.append(f"Slide {slide.get('slide_number', '?')}: {slide.get('title', '')}")
                lines.append(f"Subtitle: {slide.get('subtitle', '')}")
                for point in slide.get('bullet_points', []):
                    lines.append(f"  - {point}")
                lines.append(f"Visual: {slide.get('visual_suggestion', '')}")
            else:
                lines.append(str(slide))
            lines.append("")
        return "\n".join(lines)

    def _format_script(self, script: list) -> str:
        """Format speaker script as text."""
        lines = ["SPEAKER SCRIPT", "=" * 50, ""]
        for section in script:
            if isinstance(section, dict):
                lines.append(f"[Slide {section.get('slide_number', '?')}] ({section.get('section', '')})")
                lines.append(f"[Tone: {section.get('tone', 'normal')}]")
                lines.append(f"")
                lines.append(f"{section.get('text', '')}")
                if section.get('notes'):
                    lines.append(f"")
                    lines.append(f"(Note: {section.get('notes', '')})")
            else:
                lines.append(str(section))
            lines.append("")
        return "\n".join(lines)

    def get_exports(self) -> list:
        """List all export files."""
        return [str(f) for f in self.export_dir.glob("*.zip")]