"""
State Machine Module
Pydantic-based state management for session persistence and workflow tracking.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class WorkflowLayer(str, Enum):
    """Workflow layers representing major phases."""
    IDLE = "idle"
    IDEATION = "ideation"
    JUDGING = "judging"
    HITL_1 = "hitl_1"  # Human-in-the-loop: Select idea
    PLANNING = "planning"
    ARCHITECTING = "architecting"
    BUILDING = "building"
    CRITIQUING = "critiquing"
    HITL_2 = "hitl_2"  # Human-in-the-loop: Review code
    PITCHING = "pitching"
    COMPLETE = "complete"
    ERROR = "error"


class AgentMessage(BaseModel):
    """Represents a message from an agent in the chat log."""
    agent: str
    agent_name: str
    emoji: str
    role: str
    message: str
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class Idea(BaseModel):
    """Represents a project idea generated by the Ideator."""
    id: int
    title: str
    description: str
    key_features: List[str] = Field(default_factory=list)
    tech_stack: List[str] = Field(default_factory=list)
    innovation_score: float = Field(ge=1, le=10)
    target_users: str


class IdeaEvaluation(BaseModel):
    """Evaluation result for an idea from the Judge."""
    idea_id: int
    idea_title: str
    scores: Dict[str, float] = Field(default_factory=dict)
    total_score: float
    strengths: List[str] = Field(default_factory=list)
    risks: List[str] = Field(default_factory=list)
    recommendation: str


class Milestone(BaseModel):
    """Project milestone from the Planner."""
    id: int
    title: str
    description: str
    tasks: List[str] = Field(default_factory=list)
    estimated_hours: int = 0
    dependencies: List[int] = Field(default_factory=list)
    deliverables: List[str] = Field(default_factory=list)


class CodeFile(BaseModel):
    """Generated code file from the Builder."""
    filepath: str
    description: str
    content: str
    language: str = "python"


class CodeIssue(BaseModel):
    """Issue found by the Critic."""
    severity: str  # critical, high, medium, low
    file: str
    line: int = 0
    description: str
    fix: str


class PitchNarrative(BaseModel):
    """Narrative structure from the Pitch Strategist."""
    problem: str
    solution: str
    demo_plan: str
    impact: str
    future_vision: str


class ColorPalette(BaseModel):
    """Color palette for the presentation."""
    primary_color: str = "#4A90E2"  # Primary brand color
    secondary_color: str = "#F5A623"  # Accent color
    background_color: str = "#FFFFFF"  # Slide background
    text_color: str = "#333333"  # Main text color
    accent_color: str = "#7ED321"  # Highlight color
    gradient_start: str = ""  # Optional gradient start
    gradient_end: str = ""  # Optional gradient end


class FontStyle(BaseModel):
    """Font style recommendations."""
    title_font: str = "Montserrat Bold"
    subtitle_font: str = "Open Sans"
    body_font: str = "Roboto"
    title_size: int = 36
    body_size: int = 18
    accent_size: int = 14


class ImageSuggestion(BaseModel):
    """Image/icon suggestion for a slide."""
    description: str = ""  # What the image should show
    icon_keywords: List[str] = Field(default_factory=list)  # Keywords for icon search
    image_type: str = "icon"  # icon, photo, illustration, chart, screenshot
    placement: str = "right"  # left, right, center, background
    opacity: float = 1.0  # Image opacity (0.0-1.0)


class TransitionStyle(BaseModel):
    """Slide transition recommendations."""
    transition_type: str = "fade"  # fade, slide, zoom, dissolve, none
    duration_ms: int = 500  # Transition duration in milliseconds
    easing: str = "ease-in-out"  # ease-in-out, linear, ease-out


class Slide(BaseModel):
    """Slide in the pitch deck - detailed specification for design tools."""
    slide_number: int
    title: str
    subtitle: str
    bullet_points: List[str] = Field(default_factory=list)
    visual_suggestion: str  # Main visual description
    design_note: str  # Layout and styling guidance
    
    # NEW: Detailed specifications for design tools (Canva, Figma, etc.)
    layout_type: str = "two-column"  # title-only, two-column, center-focus, full-bleed, grid
    content_sections: List[str] = Field(default_factory=list)  # Detailed content for each section
    icon_suggestions: List[ImageSuggestion] = Field(default_factory=list)  # Icon/image recommendations
    background_style: str = "solid"  # solid, gradient, image, pattern
    color_overrides: Optional[ColorPalette] = None  # Per-slide color overrides
    animation_notes: str = ""  # Animation suggestions for this slide
    speaker_script: str = ""  # What to say for this slide
    estimated_duration_seconds: int = 30  # How long to spend on this slide
    canva_template_hint: str = ""  # Suggested Canva template type


class ScriptSection(BaseModel):
    """Section of the speaker script."""
    slide_number: int
    section: str
    text: str
    duration_seconds: int = 0
    tone: str = "normal"
    notes: str = ""


class SessionState(BaseModel):
    """
    Main state machine for a hackathon session.
    Tracks all data across workflow layers with JSON persistence support.
    """
    # Session identification
    session_id: str
    theme: str = ""
    constraints: str = ""

    # Workflow tracking
    current_layer: WorkflowLayer = WorkflowLayer.IDLE
    previous_layer: Optional[WorkflowLayer] = None
    is_paused: bool = False
    pause_reason: str = ""

    # Layer 1: Ideation
    ideas: List[Idea] = Field(default_factory=list)
    evaluations: List[IdeaEvaluation] = Field(default_factory=list)
    selected_idea: Optional[Idea] = None
    user_feedback_1: Dict[str, Any] = Field(default_factory=dict)

    # Layer 2: Development
    milestones: List[Milestone] = Field(default_factory=list)
    architecture: Dict[str, Any] = Field(default_factory=dict)
    code_artifacts: Dict[str, CodeFile] = Field(default_factory=dict)
    critic_report: Dict[str, Any] = Field(default_factory=dict)
    user_feedback_2: Dict[str, Any] = Field(default_factory=dict)
    refinement_count: int = 0
    max_refinements: int = 3

    # Layer 3: Pitch
    narrative: Optional[PitchNarrative] = None
    slides: List[Slide] = Field(default_factory=list)
    script: List[ScriptSection] = Field(default_factory=list)

    # Communication log
    agent_log: List[AgentMessage] = Field(default_factory=list)

    # Error tracking
    error_message: Optional[str] = None

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        """Convert state to dictionary for JSON serialization."""
        return self.model_dump(mode='json')

    def add_agent_message(self, agent: str, agent_name: str, emoji: str, role: str, message: str, metadata: Optional[Dict[str, Any]] = None):
        """Add a message to the agent communication log."""
        msg = AgentMessage(
            agent=agent,
            agent_name=agent_name,
            emoji=emoji,
            role=role,
            message=message,
            metadata=metadata or {}
        )
        self.agent_log.append(msg)
        self.updated_at = datetime.now()

    def transition_to(self, new_layer: WorkflowLayer):
        """Transition to a new workflow layer."""
        self.previous_layer = self.current_layer
        self.current_layer = new_layer
        self.updated_at = datetime.now()

    def pause_for_hitl(self, reason: str):
        """Pause the workflow for human-in-the-loop input."""
        self.is_paused = True
        self.pause_reason = reason
        self.updated_at = datetime.now()

    def resume(self):
        """Resume the workflow after human input."""
        self.is_paused = False
        self.pause_reason = ""
        self.updated_at = datetime.now()

    def set_error(self, message: str):
        """Set error state."""
        self.current_layer = WorkflowLayer.ERROR
        self.error_message = message
        self.updated_at = datetime.now()